### PR TITLE
update: added new cnn model

### PR DESCRIPTION
**Pull request by vidriduch**
- model_cnn.py - added new vgg-net style cnn model
- utils.py - added new function for loading datasets from folders with
           augmentation as numpy arrrays
- added some visualization functions

### CODE REVIEW

**Comment by vidriduch** [comment]
@mrshu I added new function for loading augmented data from folder as dataset generator. I think this deserves a review. :)

**Comment by mrshu** [comment]
@Foxiy Please fix merge conflict.

**Comment by vidriduch** [comment]
@mrshu I fixed the conflict. I believe this is ready for another pass.

**Comment by mrshu** [comment]
@Foxiy Dobre teta.

**Pull request merged**
